version: "3.9"

services:
  minio:
    restart: always
    container_name: minio_mem
    image: minio/minio:latest
    command: server --console-address ":${MINIO_PORT_2}" /data/
    ports:
      - ${MINIO_PORT_1}:${MINIO_PORT_1}
      - ${MINIO_PORT_2}:${MINIO_PORT_2}
    env_file:
      - .env
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    restart: always
    container_name: postgres_mem
    image: postgres:15
    volumes:
      - postgres_storage:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

volumes:
  minio-storage:
  postgres_storage:

