services:
  minio:
    restart: always
    container_name: minio_mem
    image: minio/minio:latest
    command: server --console-address ":${MINIO_PORT_2}" /data/
    ports:
      - ${MINIO_PORT_1}:${MINIO_PORT_1}
      - ${MINIO_PORT_2}:${MINIO_PORT_2}
    env_file:
      - .env
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  postgres:
    restart: always
    container_name: postgres_mem
    image: postgres:15
    volumes:
      - postgres_storage:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

  meme_center:
    restart: always
    container_name: meme_center
    build:
      context: .
      dockerfile: "meme_center_dockerfile"
    env_file:
      - .env_meme_center
    ports:
      - 8006:8006
    depends_on:
        - postgres
        - minio
    volumes:
      - ./meme_center:/meme_center

  image_store:
    restart: always
    container_name: image_store
    build:
      context: .
      dockerfile: "image_store_dockerfile"
    env_file:
      - .env_image_store
    ports:
      - 8005:8005
    depends_on:
      - minio
    volumes:
      - ./image_store:/image_store
volumes:
  minio-storage:
  postgres_storage:

